export default {
	theme:null,
	event_player:null,
	search:[],
	screen_content_detail:0,
	screen_content_search:0,
	screen_search:0,
	novedades:null,
	navigator:{
		route: null,
		params:{}
	},
	intro: null,
	history_login: null,
	player_controls:{},
	google_cast:{},
	toast:{},
	mi_lista_mix: {},
	estas_viendo: {},
	drawer:null,
	loading:false,
	watchlater: false,
	info_user:{},
	contents:{},
	profiles:[],
	content_info:{},
	configuration:{},
	marketing: {},
	genres: [],
}